### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by 0xluk** [qubic/go-archiver#16]
Rationale:

In order to have a way to detect if an archive node is synced up, we need a healthcheck endpoint.

We should define a threshold equal to 2 (preferably configurable) 
This should compare `lastProcessingTick` with `currentTickInfo` of a qubic node, and if `(currentTickInfo - lastProcessingTick) > threshold` endpoint should return a non 2xx http status code, otherwise 200.

Things to consider:
- Getting currentTickInfo only from a node is not desirable. There is an edgecase that we want to cover: If a bad node is reporting a very high tick, the condition will always be false and the system will be put offline. To avoid that we want to query multiple nodes (from the pool) sort them and check if the biggest one is not very big compared to the 2nd biggest (edgecase described above). If indeed it's higher than the 2nd with more than 50 ticks for example, then real currentTickInfo is 2nd biggest.

**Comment by LINCKODE** [comment]
Implemented endpoint, not tested yet.
Implemented threshold feature, with configuration. Might have to update docker compose files to support this.
Network tick is fetched from a new endpoint (`/chain-tick`) in node-fetcher.
Will have to implement check for higher than normal tick in node-fetcher.

**Comment by LINCKODE** [comment]
Check hash been implemented.
Ready for review.

**Comment by LINCKODE** [comment]
Check has been implemented.
Will have to look into using endpoint with traefik

**Comment by LINCKODE** [comment]
Added traefik configuration.
Ready for review.
