### ISSUE TITLE
Storing and exposing 'Send Many' transfers

### ISSUE THREAD

**Issue by LINCKODE** [qubic/go-archiver#29]

**Comment by 0xluk** [comment]
Given the fact that we need to track balance changes by send many smart contract, I have the following approach in mind:
**Filtering**
When we perform a tick validation, we need to search for send many transactions (defined by recv addr `EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVWRF`, tx type `1` and maybe input size `1000`)
**Storing**
For each send many transaction, we need to store the following in the persistance layer by using the tx id as the key:
- sender address `SourceId`
- moneyFlew `moneyFlew`
- a list of transfers [destAddr, amount] `[destId, amount]`

**Exposing via rpc**
Given the fact that the only index is the tx id, one can request the send many transfers and receive the above information stored in db

**Comment by 0xluk** [comment]
It will be done as part of the go-transfers repository/service
