### ISSUE TITLE
API error after node upgrade

### ISSUE THREAD

**Issue by COLUD4** [qubic/go-archiver#52]
ghcr.io/qubic/qubic-http:v0.7.0
ghcr.io/qubic/qubic-archiver:v0.6.1
ghcr.io/qubic/qubic-nodes:v1.0.4
curl http://127.0.0.1:8001/healthcheck| jq
{
  "code": 5,
  "message": "Not Found",
  "details": []
}

**Comment by LINCKODE** [comment]
Hello there!
We have changed the archiver API to require a `/v1/` prefix. This was done to facilitate the v2 endpoints.
If you are using Traefik with docker compose, make sure the to add the `/v1/` prefix to the health check option.
